2025-04-23 07:19:07,380 ERROR scheduler Skipped queueing erpnext.stock.doctype.serial_no.serial_no.update_maintenance_status because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,741 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,747 ERROR scheduler Skipped queueing erpnext.assets.doctype.asset.depreciation.post_depreciation_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,759 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,767 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_contacts.google_contacts.sync because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,773 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,779 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,790 ERROR scheduler Skipped queueing erpnext.crm.doctype.email_campaign.email_campaign.set_email_campaign_status because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,797 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,802 ERROR scheduler Skipped queueing erpnext.accounts.doctype.process_statement_of_accounts.process_statement_of_accounts.send_auto_email because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,809 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,815 ERROR scheduler Skipped queueing erpnext.setup.doctype.email_digest.email_digest.send because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,821 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,828 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.collect_project_status because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,835 ERROR scheduler Skipped queueing erpnext.crm.utils.open_leads_opportunities_based_on_todays_event because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,843 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_tool.bom_update_tool.auto_update_latest_price_in_all_boms because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,854 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,860 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_drive.google_drive.daily_backup because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,867 ERROR scheduler Skipped queueing erpnext.controllers.accounts_controller.update_invoice_status because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,875 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,881 ERROR scheduler Skipped queueing erpnext.setup.doctype.company.company.cache_companies_monthly_sales_history because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,896 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,909 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,918 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,929 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,937 ERROR scheduler Skipped queueing erpnext.stock.doctype.serial_no.serial_no.update_maintenance_status because it was found in queue for GalaxyERP.com
2025-04-23 07:20:03,950 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,199 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,207 ERROR scheduler Skipped queueing erpnext.accounts.doctype.process_statement_of_accounts.process_statement_of_accounts.send_auto_email because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,217 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_tool.bom_update_tool.auto_update_latest_price_in_all_boms because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,223 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,231 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.collect_project_status because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,247 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,256 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,262 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,268 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,274 ERROR scheduler Skipped queueing erpnext.assets.doctype.asset.depreciation.post_depreciation_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,285 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,297 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,306 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,314 ERROR scheduler Skipped queueing erpnext.setup.doctype.email_digest.email_digest.send because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,320 ERROR scheduler Skipped queueing erpnext.setup.doctype.company.company.cache_companies_monthly_sales_history because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,329 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_drive.google_drive.daily_backup because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,337 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,362 ERROR scheduler Skipped queueing erpnext.crm.doctype.email_campaign.email_campaign.set_email_campaign_status because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,372 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,384 ERROR scheduler Skipped queueing erpnext.crm.utils.open_leads_opportunities_based_on_todays_event because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,395 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for GalaxyERP.com
2025-04-23 07:21:02,402 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,546 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,556 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_tool.bom_update_tool.auto_update_latest_price_in_all_boms because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,574 ERROR scheduler Skipped queueing erpnext.assets.doctype.asset.depreciation.post_depreciation_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,581 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,596 ERROR scheduler Skipped queueing erpnext.setup.doctype.email_digest.email_digest.send because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,606 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,612 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,631 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,638 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_drive.google_drive.daily_backup because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,645 ERROR scheduler Skipped queueing erpnext.crm.utils.open_leads_opportunities_based_on_todays_event because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,657 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,673 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,679 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.collect_project_status because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,686 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for GalaxyERP.com
2025-04-23 07:21:58,712 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,864 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,888 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,896 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,901 ERROR scheduler Skipped queueing erpnext.setup.doctype.email_digest.email_digest.send because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,910 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,938 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,950 ERROR scheduler Skipped queueing erpnext.assets.doctype.asset.depreciation.post_depreciation_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,955 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,964 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:22:54,971 ERROR scheduler Skipped queueing erpnext.crm.utils.open_leads_opportunities_based_on_todays_event because it was found in queue for GalaxyERP.com
2025-04-23 07:22:55,002 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_drive.google_drive.daily_backup because it was found in queue for GalaxyERP.com
2025-04-23 07:22:55,015 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_tool.bom_update_tool.auto_update_latest_price_in_all_boms because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,076 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_tool.bom_update_tool.auto_update_latest_price_in_all_boms because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,106 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,114 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,138 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,155 ERROR scheduler Skipped queueing erpnext.assets.doctype.asset.depreciation.post_depreciation_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,163 ERROR scheduler Skipped queueing erpnext.setup.doctype.email_digest.email_digest.send because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,177 ERROR scheduler Skipped queueing erpnext.crm.utils.open_leads_opportunities_based_on_todays_event because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,192 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,215 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:23:51,229 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_drive.google_drive.daily_backup because it was found in queue for GalaxyERP.com
2025-04-23 07:24:47,496 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:24:47,510 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:24:47,552 ERROR scheduler Skipped queueing erpnext.crm.utils.open_leads_opportunities_based_on_todays_event because it was found in queue for GalaxyERP.com
2025-04-23 07:24:47,594 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:24:47,602 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for GalaxyERP.com
2025-04-23 07:24:47,660 ERROR scheduler Skipped queueing erpnext.assets.doctype.asset.depreciation.post_depreciation_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:25:43,641 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for GalaxyERP.com
2025-04-23 07:25:43,668 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,608 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,617 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.hourly_reminder because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,626 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,652 ERROR scheduler Skipped queueing erpnext.utilities.doctype.video.video.update_youtube_data because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,667 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,673 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,679 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,713 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,722 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,728 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,734 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,744 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,757 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,766 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,782 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,793 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for GalaxyERP.com
2025-04-23 07:31:23,802 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.project_status_update_reminder because it was found in queue for GalaxyERP.com
2025-04-23 07:32:19,996 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,004 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.hourly_reminder because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,009 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,019 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,041 ERROR scheduler Skipped queueing erpnext.utilities.doctype.video.video.update_youtube_data because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,057 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.project_status_update_reminder because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,063 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,083 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,099 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,111 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,131 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,152 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for GalaxyERP.com
2025-04-23 07:32:20,163 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for GalaxyERP.com
2025-04-23 07:33:16,335 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.project_status_update_reminder because it was found in queue for GalaxyERP.com
2025-04-23 07:33:16,374 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for GalaxyERP.com
2025-04-23 07:33:16,385 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.hourly_reminder because it was found in queue for GalaxyERP.com
2025-04-23 07:33:16,449 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:33:16,471 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for GalaxyERP.com
2025-04-23 07:33:16,482 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for GalaxyERP.com
2025-04-23 07:34:14,366 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for GalaxyERP.com
2025-04-23 07:34:14,456 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:35:10,048 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for GalaxyERP.com
2025-04-23 07:35:10,055 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for GalaxyERP.com
2025-04-23 07:35:10,079 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for GalaxyERP.com
2025-04-23 07:35:10,148 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for GalaxyERP.com
2025-04-23 07:46:26,535 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for GalaxyERP.com
2025-04-23 07:46:26,677 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for GalaxyERP.com
2025-04-23 07:46:26,765 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for GalaxyERP.com
2025-04-23 07:47:23,066 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for GalaxyERP.com
2025-04-23 07:53:58,914 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:23:24,043 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:24:20,555 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:25:16,968 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:26:13,455 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:27:11,616 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:28:08,003 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:33:26,716 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:34:23,076 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:35:19,410 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:36:17,672 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:37:13,796 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:38:10,102 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:55:35,567 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:56:31,811 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:57:27,958 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:58:24,331 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 09:59:20,340 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 10:00:18,523 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 10:01:41,679 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
2025-04-23 10:02:37,859 ERROR scheduler Exception in Enqueue Events for Site GalaxyERP.com
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
      ^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/mnt/c/Users/Admin/OneDrive/Desktop/GalaxyERP/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
